name: Build and Tag on Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml

  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          tag=$(git describe --tags --abbrev=0 || echo v0.0.0)
          echo "latest_tag=$tag" >> $GITHUB_ENV

      - name: Bump Patch Version
        id: bump
        run: |
          latest=${{ env.latest_tag }}
          IFS='.' read -r major minor patch <<< "${latest#v}"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

  release:
    name: Release Image
    needs: tag
    uses: ./.github/workflows/release-image.yaml
    with:
      version: ${{ needs.tag.outputs.new_tag }}
